# Generated by Django 5.2.9 on 2025-12-27 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('aircraft_type', models.CharField(choices=[('plane', 'Самолёт'), ('helicopter', 'Вертолёт')], max_length=20, verbose_name='Тип')),
                ('seats', models.PositiveIntegerField(verbose_name='Количество мест')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=150, verbose_name='Направление')),
                ('departure_time', models.DateTimeField(verbose_name='Время вылёта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=150, verbose_name='ФИО пассажира')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата бронирования')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airport.flight')),
            ],
        ),
    ]
